import React from "react";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from "@/components/ui/carousel";
import ThemeToggle from "@/components/ThemeToggle";
import { ThemeProvider } from "next-themes";

// Sample gallery images (could be mock generations)
const GALLERY_IMAGES = [
  "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80",
  "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80",
  "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80",
  "https://images.unsplash.com/photo-1465101162946-4377e57745c3?auto=format&fit=crop&w=400&q=80",
];

const PRODUCT = {
  name: "Customizable Coffee Cup",
  price: "$8.99",
  description:
    "Design your own coffee cup! Generate a unique image using our AI chat and place it on your personal mockup.",
  img: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=600&q=80",
};

const Index = () => {
  return (
    <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
      <div className="min-h-screen flex flex-col items-center justify-center bg-background py-10 px-2 sm:px-4 md:px-6 relative">
        {/* Theme toggle top right */}
        <div className="absolute right-4 top-4 z-50">
          <ThemeToggle />
        </div>
        {/* Hero section */}
        <div className="w-full max-w-4xl mx-auto grid grid-cols-1 md:grid-cols-12 gap-6 md:gap-10 place-items-center">
          <div className="col-span-1 md:col-span-6 flex flex-col justify-center items-start gap-6 order-2 md:order-1 text-left w-full">
            <h1 className="text-3xl xs:text-4xl sm:text-5xl font-extrabold tracking-tight leading-tight mb-2">
              Make your <span className="text-primary">perfect coffee cup</span>
            </h1>
            <p className="text-base xs:text-lg sm:text-xl text-muted-foreground mb-2">
              Generate your own artwork using a chat and see it instantly on the cup mockup. Try descriptors like <em>"floral design"</em>, <em>"space cat"</em>, or your own ideas!
            </p>
            <p className="text-lg sm:text-xl font-semibold mb-3 text-primary">{PRODUCT.price}</p>
            <Link to="/product" className="w-full sm:w-auto">
              <Button
                size="lg"
                className="w-full sm:w-auto px-8 sm:px-10 py-4 sm:py-5 text-base sm:text-lg shadow-lg transition hover:scale-105"
              >
                Start Customizing
              </Button>
            </Link>
          </div>
          <div className="col-span-1 md:col-span-6 flex justify-center w-full max-w-xs sm:max-w-md md:max-w-md order-1 md:order-2">
            <img
              src={PRODUCT.img}
              alt={PRODUCT.name}
              className="rounded-2xl shadow-xl w-full object-cover border bg-white aspect-square max-w-[320px] sm:max-w-md"
              draggable={false}
            />
          </div>
        </div>

        {/* How it works CTA section */}
        <div className="w-full max-w-2xl mx-auto mt-12 md:mt-16 mb-5 px-1 sm:px-4">
          <div className="bg-secondary/40 rounded-2xl p-5 sm:p-8 flex flex-col items-center shadow-md text-center gap-4">
            <h2 className="text-xl sm:text-2xl font-bold">How it works:</h2>
            <ol className="list-decimal list-inside text-muted-foreground text-base sm:text-lg space-y-2 text-left sm:text-center">
              <li>
                <b>Chat:</b> Describe any image you want (e.g. &quot;cat in a space suit&quot;, &quot;colorful flowers&quot;).
              </li>
              <li>
                <b>Pick:</b> Choose one of <span className="font-semibold text-primary">4 images</span> generated by AI.
              </li>
              <li>
                <b>Preview:</b> Instantly see your art on the coffee cup mockup!
              </li>
              <li>
                <b>Order:</b> Get your unique coffee cup shipped to you.
              </li>
            </ol>
            <Link to="/product">
              <Button className="mt-2 px-8 py-3 text-base sm:text-lg">
                Try it now
              </Button>
            </Link>
          </div>
        </div>

        {/* Carousel section */}
        <div className="w-full max-w-2xl mx-auto mt-6 sm:mt-12 mb-5 px-1 sm:px-4">
          <h3 className="text-lg sm:text-xl font-semibold text-center mb-3">See recent coffee cup designs</h3>
          <div className="relative">
            <Carousel
              className="sm:w-[340px] md:w-[400px] w-full mx-auto"
              opts={{ loop: true }}
            >
              <CarouselContent>
                {GALLERY_IMAGES.map((url, i) => (
                  <CarouselItem key={i} className="flex justify-center">
                    <img
                      src={url}
                      loading="lazy"
                      alt={`Sample mug ${i + 1}`}
                      className="rounded-lg border shadow aspect-square w-44 xs:w-48 sm:w-64 object-cover bg-white"
                      draggable={false}
                    />
                  </CarouselItem>
                ))}
              </CarouselContent>
              <CarouselPrevious />
              <CarouselNext />
            </Carousel>
          </div>
        </div>

        <div className="mt-8 text-muted-foreground text-sm max-w-xl text-center px-2 pb-8">
          <span className="font-semibold">Tip:</span> After describing your desired image in the chat, you'll choose one of four generated options. Your pick instantly updates the product mock!
        </div>
      </div>
    </ThemeProvider>
  );
};

export default Index;
